// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function IsFrameless():Promise<boolean>;

export function LogPrintln(arg1:string):Promise<number>;
